<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yujianghuai</groupId>
        <artifactId>yujianghuai-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yujianghuai-common</artifactId>
    <name>yujianghuai-common</name>
    <packaging>pom</packaging>

    <modules>
        <module>yujianghuai-common-core</module>
        <module>yujianghuai-common-web</module>
        <module>yujianghuai-common-tenant</module>
        <module>yujianghuai-common-feign</module>
        <module>yujianghuai-common-mq</module>
        <module>yujianghuai-common-data</module>
        <module>yujianghuai-common-mybatis</module>
    </modules>
</project>
