package com.yujianghuai.nacos.config;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class NacosConfigFileWriter {

    private final NacosManagerProperties properties;

    public NacosConfigFileWriter(NacosManagerProperties properties) {
        this.properties = properties;
    }

    public void prepareApplicationProperties() {
        NacosManagerProperties.Database database = properties.getDatabase();
        if (database == null || !database.isEnabled()) {
            return;
        }
        if (database.getUrls() == null || database.getUrls().isEmpty()) {
            throw new IllegalStateException("nacos.manager.database.urls must not be empty when database is enabled");
        }

        Path configPath = resolveConfigPath();
        Map<String, String> overrides = buildDatabaseOverrides(database);

        try {
            List<String> originalLines = Files.exists(configPath)
                    ? Files.readAllLines(configPath, StandardCharsets.UTF_8)
                    : new ArrayList<>();
            Files.write(configPath, mergeProperties(originalLines, overrides), StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("failed to write nacos config file: " + exception.getMessage(), exception);
        }
    }

    private Path resolveConfigPath() {
        String home = properties.getHome();
        if (home == null || home.isBlank()) {
            throw new IllegalStateException("NACOS_HOME is missing, please set nacos.manager.home or NACOS_HOME");
        }

        Path configPath = Path.of(home).resolve("conf").resolve("application.properties");
        Path configDir = configPath.getParent();
        if (!Files.exists(configDir)) {
            throw new IllegalStateException("nacos conf directory not found: " + configDir);
        }
        return configPath;
    }

    private Map<String, String> buildDatabaseOverrides(NacosManagerProperties.Database database) {
        Map<String, String> overrides = new LinkedHashMap<>();
        String platform = database.getPlatform();
        overrides.put("spring.datasource.platform", platform);
        overrides.put("spring.sql.init.platform", platform);
        overrides.put("db.num", String.valueOf(database.getUrls().size()));
        for (int index = 0; index < database.getUrls().size(); index++) {
            overrides.put("db.url." + index, database.getUrls().get(index));
        }
        overrides.put("db.user", database.getUsername());
        overrides.put("db.password", database.getPassword());
        database.getPool().forEach((key, value) -> overrides.put("db.pool.config." + key, value));
        return overrides;
    }

    private List<String> mergeProperties(List<String> originalLines, Map<String, String> overrides) {
        List<String> result = new ArrayList<>();
        Map<String, String> remaining = new LinkedHashMap<>(overrides);

        for (String line : originalLines) {
            String key = parsePropertyKey(line);
            if (key != null && remaining.containsKey(key)) {
                result.add(key + "=" + remaining.remove(key));
            } else {
                result.add(line);
            }
        }

        if (!remaining.isEmpty()) {
            result.add("");
            result.add("# Generated by yujianghuai-nacos");
            remaining.forEach((key, value) -> result.add(key + "=" + value));
        }
        return result;
    }

    private String parsePropertyKey(String line) {
        String trimmed = line.trim();
        if (trimmed.isEmpty() || trimmed.startsWith("#")) {
            return null;
        }

        int equalsIndex = trimmed.indexOf('=');
        if (equalsIndex <= 0) {
            return null;
        }
        return trimmed.substring(0, equalsIndex).trim();
    }
}
