-- 基金业务表
-- 依赖 db/yujianghuai-sys.sql 中已创建的 sys_tenant、sys_user 等系统表。

SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS `yujianghuai`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE `yujianghuai`;

CREATE TABLE IF NOT EXISTS `biz_fund_info` (
    `id` BIGINT NOT NULL COMMENT '基金主键ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码',
    `fund_name` VARCHAR(128) NOT NULL COMMENT '基金名称',
    `fund_short_name` VARCHAR(64) DEFAULT NULL COMMENT '基金简称',
    `fund_type` VARCHAR(32) NOT NULL COMMENT '基金类型: STOCK股票型 BOND债券型 MIXED混合型 INDEX指数型 MONEY货币型 QDII等',
    `fund_company` VARCHAR(128) DEFAULT NULL COMMENT '基金公司',
    `manager_name` VARCHAR(128) DEFAULT NULL COMMENT '基金经理',
    `risk_level` TINYINT DEFAULT NULL COMMENT '风险等级: 1低 2中低 3中 4中高 5高',
    `establish_date` DATE DEFAULT NULL COMMENT '成立日期',
    `currency` VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `tracking_index` VARCHAR(128) DEFAULT NULL COMMENT '跟踪指数',
    `purchase_status` TINYINT NOT NULL DEFAULT 1 COMMENT '申购状态: 0暂停 1开放',
    `redeem_status` TINYINT NOT NULL DEFAULT 1 COMMENT '赎回状态: 0暂停 1开放',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '基金状态: 0失效 1正常 2清盘',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_fund_info_tenant_code` (`tenant_id`, `fund_code`),
    KEY `idx_biz_fund_info_name` (`tenant_id`, `fund_name`),
    KEY `idx_biz_fund_info_type` (`tenant_id`, `fund_type`, `status`),
    CONSTRAINT `fk_biz_fund_info_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金基础信息表';

CREATE TABLE IF NOT EXISTS `biz_fund_tag` (
    `id` BIGINT NOT NULL COMMENT '标签ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `tag_name` VARCHAR(64) NOT NULL COMMENT '标签名称',
    `tag_type` VARCHAR(32) NOT NULL DEFAULT 'CUSTOM' COMMENT '标签类型: STYLE风格 INDUSTRY行业 THEME主题 CUSTOM自定义',
    `tag_color` VARCHAR(32) DEFAULT NULL COMMENT '标签颜色',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0禁用 1启用',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_fund_tag_name` (`tenant_id`, `tag_name`),
    KEY `idx_biz_fund_tag_type` (`tenant_id`, `tag_type`, `status`),
    CONSTRAINT `fk_biz_fund_tag_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金标签表';

CREATE TABLE IF NOT EXISTS `biz_fund_tag_relation` (
    `id` BIGINT NOT NULL COMMENT '关系ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `tag_id` BIGINT NOT NULL COMMENT '标签ID，关联biz_fund_tag.id',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_fund_tag_relation` (`tenant_id`, `fund_id`, `tag_id`),
    KEY `idx_biz_fund_tag_relation_tag` (`tenant_id`, `tag_id`),
    CONSTRAINT `fk_biz_fund_tag_rel_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_fund_tag_rel_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_fund_tag_rel_tag` FOREIGN KEY (`tag_id`) REFERENCES `biz_fund_tag` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金标签关系表';

CREATE TABLE IF NOT EXISTS `biz_fund_nav` (
    `id` BIGINT NOT NULL COMMENT '净值ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `nav_date` DATE NOT NULL COMMENT '净值日期',
    `unit_nav` DECIMAL(18,6) NOT NULL COMMENT '单位净值',
    `accumulated_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '累计净值',
    `daily_growth_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '日涨跌幅百分比',
    `source` VARCHAR(64) DEFAULT NULL COMMENT '数据来源',
    `source_update_time` DATETIME(0) DEFAULT NULL COMMENT '来源更新时间',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_fund_nav_date` (`tenant_id`, `fund_id`, `nav_date`),
    KEY `idx_biz_fund_nav_code_date` (`tenant_id`, `fund_code`, `nav_date`),
    CONSTRAINT `fk_biz_fund_nav_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_fund_nav_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金历史净值表';

CREATE TABLE IF NOT EXISTS `biz_fund_realtime_estimate` (
    `id` BIGINT NOT NULL COMMENT '实时估值ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `estimate_time` DATETIME(0) NOT NULL COMMENT '估值时间',
    `estimate_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '预估单位净值',
    `estimate_growth_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '预估涨跌幅百分比',
    `estimate_amount` DECIMAL(20,4) DEFAULT NULL COMMENT '预估净值变动金额',
    `previous_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '上一交易日单位净值',
    `market_status` VARCHAR(32) NOT NULL DEFAULT 'TRADING' COMMENT '市场状态: TRADING交易中 CLOSED已收盘',
    `source` VARCHAR(64) DEFAULT NULL COMMENT '数据来源',
    `source_update_time` DATETIME(0) DEFAULT NULL COMMENT '来源更新时间',
    `abnormal_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '异常标记: 0正常 1异常',
    `abnormal_reason` VARCHAR(512) DEFAULT NULL COMMENT '异常原因',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_fund_estimate_time` (`tenant_id`, `fund_id`, `estimate_time`),
    KEY `idx_biz_fund_estimate_code_time` (`tenant_id`, `fund_code`, `estimate_time`),
    CONSTRAINT `fk_biz_fund_est_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_fund_est_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金实时估值表';

CREATE TABLE IF NOT EXISTS `biz_fund_dividend` (
    `id` BIGINT NOT NULL COMMENT '分红ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `record_date` DATE DEFAULT NULL COMMENT '权益登记日',
    `ex_dividend_date` DATE DEFAULT NULL COMMENT '除息日',
    `payment_date` DATE DEFAULT NULL COMMENT '派息日',
    `dividend_per_share` DECIMAL(18,6) NOT NULL COMMENT '每份分红金额',
    `dividend_type` VARCHAR(32) NOT NULL DEFAULT 'CASH' COMMENT '分红方式: CASH现金分红 REINVEST红利再投资',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_fund_dividend_date` (`tenant_id`, `fund_id`, `ex_dividend_date`),
    KEY `idx_biz_fund_dividend_code` (`tenant_id`, `fund_code`),
    CONSTRAINT `fk_biz_fund_dividend_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_fund_dividend_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='基金分红记录表';

CREATE TABLE IF NOT EXISTS `biz_user_portfolio` (
    `id` BIGINT NOT NULL COMMENT '投资组合ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_name` VARCHAR(128) NOT NULL COMMENT '组合名称',
    `portfolio_type` VARCHAR(32) NOT NULL DEFAULT 'CUSTOM' COMMENT '组合类型: DEFAULT默认 CUSTOM自定义',
    `target_amount` DECIMAL(20,4) DEFAULT NULL COMMENT '目标金额',
    `risk_preference` TINYINT DEFAULT NULL COMMENT '风险偏好: 1保守 2稳健 3平衡 4积极 5激进',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0停用 1启用',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_portfolio_name` (`tenant_id`, `user_id`, `portfolio_name`),
    KEY `idx_biz_user_portfolio_user` (`tenant_id`, `user_id`, `status`),
    CONSTRAINT `fk_biz_user_portfolio_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_portfolio_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户投资组合表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_group` (
    `id` BIGINT NOT NULL COMMENT '分组ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_id` BIGINT DEFAULT NULL COMMENT '投资组合ID，关联biz_user_portfolio.id',
    `group_name` VARCHAR(128) NOT NULL COMMENT '分组名称',
    `group_type` VARCHAR(32) NOT NULL DEFAULT 'CUSTOM' COMMENT '分组类型: SYSTEM系统分组 CUSTOM自定义分组',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0禁用 1启用',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_fund_group_name` (`tenant_id`, `user_id`, `portfolio_id`, `group_name`),
    KEY `idx_biz_user_fund_group_user` (`tenant_id`, `user_id`, `sort_order`),
    KEY `idx_biz_user_fund_group_portfolio` (`tenant_id`, `portfolio_id`),
    CONSTRAINT `fk_biz_user_fund_group_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_fund_group_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_fund_group_portfolio` FOREIGN KEY (`portfolio_id`) REFERENCES `biz_user_portfolio` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金分组表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_holding` (
    `id` BIGINT NOT NULL COMMENT '持仓ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_id` BIGINT DEFAULT NULL COMMENT '投资组合ID，关联biz_user_portfolio.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `fund_name` VARCHAR(128) NOT NULL COMMENT '基金名称，冗余用于展示',
    `holding_shares` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持有份额',
    `available_shares` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '可用份额',
    `frozen_shares` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '冻结份额',
    `cost_amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持仓成本金额',
    `cost_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '持仓成本净值',
    `market_value` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '当前市值',
    `latest_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '最新单位净值',
    `latest_nav_date` DATE DEFAULT NULL COMMENT '最新净值日期',
    `today_estimated_value` DECIMAL(20,4) DEFAULT NULL COMMENT '当日估算市值',
    `today_profit` DECIMAL(20,4) DEFAULT NULL COMMENT '当日收益',
    `holding_profit` DECIMAL(20,4) DEFAULT NULL COMMENT '持有收益',
    `holding_profit_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '持有收益率百分比',
    `first_buy_date` DATE DEFAULT NULL COMMENT '首次买入日期',
    `last_trade_time` DATETIME(0) DEFAULT NULL COMMENT '最近交易时间',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0清仓 1持有',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_fund_holding_fund` (`tenant_id`, `user_id`, `portfolio_id`, `fund_id`),
    KEY `idx_biz_user_fund_holding_user` (`tenant_id`, `user_id`, `status`),
    KEY `idx_biz_user_fund_holding_code` (`tenant_id`, `fund_code`),
    KEY `idx_biz_user_fund_holding_profit` (`tenant_id`, `user_id`, `holding_profit_rate`),
    CONSTRAINT `fk_biz_user_holding_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_holding_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_holding_portfolio` FOREIGN KEY (`portfolio_id`) REFERENCES `biz_user_portfolio` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_holding_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金持仓表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_group_relation` (
    `id` BIGINT NOT NULL COMMENT '关系ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `group_id` BIGINT NOT NULL COMMENT '分组ID，关联biz_user_fund_group.id',
    `holding_id` BIGINT NOT NULL COMMENT '持仓ID，关联biz_user_fund_holding.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '组内排序',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_group_relation` (`tenant_id`, `group_id`, `holding_id`),
    KEY `idx_biz_user_group_relation_user` (`tenant_id`, `user_id`, `group_id`),
    KEY `idx_biz_user_group_relation_fund` (`tenant_id`, `fund_id`),
    CONSTRAINT `fk_biz_user_group_rel_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_group_rel_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_group_rel_group` FOREIGN KEY (`group_id`) REFERENCES `biz_user_fund_group` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_group_rel_holding` FOREIGN KEY (`holding_id`) REFERENCES `biz_user_fund_holding` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_group_rel_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金分组关系表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_transaction` (
    `id` BIGINT NOT NULL COMMENT '交易记录ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_id` BIGINT DEFAULT NULL COMMENT '投资组合ID，关联biz_user_portfolio.id',
    `holding_id` BIGINT DEFAULT NULL COMMENT '持仓ID，关联biz_user_fund_holding.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `fund_name` VARCHAR(128) NOT NULL COMMENT '基金名称，冗余用于展示',
    `trade_type` VARCHAR(32) NOT NULL COMMENT '交易类型: BUY申购 SELL赎回 SWITCH转换 DIVIDEND分红 SIP定投 ADJUST调整',
    `trade_status` VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED' COMMENT '交易状态: PENDING待确认 CONFIRMED已确认 FAILED失败 CANCELED已取消',
    `trade_time` DATETIME(0) NOT NULL COMMENT '交易时间',
    `confirm_date` DATE DEFAULT NULL COMMENT '确认日期',
    `amount` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '交易金额',
    `fee` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '手续费',
    `confirm_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '确认净值',
    `confirm_shares` DECIMAL(20,4) DEFAULT NULL COMMENT '确认份额',
    `before_shares` DECIMAL(20,4) DEFAULT NULL COMMENT '交易前份额',
    `after_shares` DECIMAL(20,4) DEFAULT NULL COMMENT '交易后份额',
    `before_amount` DECIMAL(20,4) DEFAULT NULL COMMENT '交易前持仓金额',
    `after_amount` DECIMAL(20,4) DEFAULT NULL COMMENT '交易后持仓金额',
    `target_fund_id` BIGINT DEFAULT NULL COMMENT '目标基金ID，转换交易时关联biz_fund_info.id',
    `target_fund_code` VARCHAR(32) DEFAULT NULL COMMENT '目标基金代码',
    `target_fund_name` VARCHAR(128) DEFAULT NULL COMMENT '目标基金名称',
    `source_channel` VARCHAR(64) DEFAULT NULL COMMENT '交易渠道',
    `external_trade_no` VARCHAR(128) DEFAULT NULL COMMENT '外部交易流水号',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_fund_trade_external` (`tenant_id`, `user_id`, `external_trade_no`),
    KEY `idx_biz_user_fund_trade_user_time` (`tenant_id`, `user_id`, `trade_time`),
    KEY `idx_biz_user_fund_trade_fund_time` (`tenant_id`, `fund_id`, `trade_time`),
    KEY `idx_biz_user_fund_trade_status` (`tenant_id`, `trade_status`, `confirm_date`),
    CONSTRAINT `fk_biz_user_trade_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_trade_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_trade_portfolio` FOREIGN KEY (`portfolio_id`) REFERENCES `biz_user_portfolio` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_trade_holding` FOREIGN KEY (`holding_id`) REFERENCES `biz_user_fund_holding` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_trade_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_trade_target_fund` FOREIGN KEY (`target_fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金交易记录表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_sip_plan` (
    `id` BIGINT NOT NULL COMMENT '定投计划ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_id` BIGINT DEFAULT NULL COMMENT '投资组合ID，关联biz_user_portfolio.id',
    `fund_id` BIGINT NOT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `fund_code` VARCHAR(32) NOT NULL COMMENT '基金代码，冗余用于查询',
    `fund_name` VARCHAR(128) NOT NULL COMMENT '基金名称，冗余用于展示',
    `plan_name` VARCHAR(128) NOT NULL COMMENT '定投计划名称',
    `amount` DECIMAL(20,4) NOT NULL COMMENT '每期定投金额',
    `frequency` VARCHAR(32) NOT NULL COMMENT '定投频率: DAILY每天 WEEKLY每周 MONTHLY每月',
    `execute_day` VARCHAR(32) DEFAULT NULL COMMENT '执行日: 周几或月内日期',
    `start_date` DATE NOT NULL COMMENT '开始日期',
    `end_date` DATE DEFAULT NULL COMMENT '结束日期',
    `next_execute_date` DATE DEFAULT NULL COMMENT '下次执行日期',
    `last_execute_date` DATE DEFAULT NULL COMMENT '上次执行日期',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0终止 1启用 2暂停',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_user_sip_plan_user` (`tenant_id`, `user_id`, `status`),
    KEY `idx_biz_user_sip_plan_execute` (`tenant_id`, `status`, `next_execute_date`),
    KEY `idx_biz_user_sip_plan_fund` (`tenant_id`, `fund_id`),
    CONSTRAINT `fk_biz_user_sip_plan_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_plan_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_plan_portfolio` FOREIGN KEY (`portfolio_id`) REFERENCES `biz_user_portfolio` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_plan_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金定投计划表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_sip_execution` (
    `id` BIGINT NOT NULL COMMENT '定投执行ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `sip_plan_id` BIGINT NOT NULL COMMENT '定投计划ID，关联biz_user_fund_sip_plan.id',
    `transaction_id` BIGINT DEFAULT NULL COMMENT '交易记录ID，关联biz_user_fund_transaction.id',
    `execute_date` DATE NOT NULL COMMENT '执行日期',
    `execute_amount` DECIMAL(20,4) NOT NULL COMMENT '执行金额',
    `execute_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '执行状态: PENDING待执行 SUCCESS成功 FAILED失败 SKIPPED跳过',
    `failure_reason` VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_sip_execution` (`tenant_id`, `sip_plan_id`, `execute_date`),
    KEY `idx_biz_user_sip_execution_user` (`tenant_id`, `user_id`, `execute_date`),
    KEY `idx_biz_user_sip_execution_status` (`tenant_id`, `execute_status`, `execute_date`),
    CONSTRAINT `fk_biz_user_sip_exec_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_exec_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_exec_plan` FOREIGN KEY (`sip_plan_id`) REFERENCES `biz_user_fund_sip_plan` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_sip_exec_trade` FOREIGN KEY (`transaction_id`) REFERENCES `biz_user_fund_transaction` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金定投执行记录表';

CREATE TABLE IF NOT EXISTS `biz_user_fund_daily_snapshot` (
    `id` BIGINT NOT NULL COMMENT '每日快照ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `portfolio_id` BIGINT DEFAULT NULL COMMENT '投资组合ID，关联biz_user_portfolio.id',
    `holding_id` BIGINT DEFAULT NULL COMMENT '持仓ID，关联biz_user_fund_holding.id',
    `fund_id` BIGINT DEFAULT NULL COMMENT '基金ID，关联biz_fund_info.id；为空表示组合汇总快照',
    `snapshot_date` DATE NOT NULL COMMENT '快照日期',
    `snapshot_type` VARCHAR(32) NOT NULL DEFAULT 'FUND' COMMENT '快照类型: FUND基金 PORTFOLIO组合 USER用户汇总',
    `total_cost` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '总成本',
    `market_value` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '市值',
    `estimated_value` DECIMAL(20,4) DEFAULT NULL COMMENT '估算市值',
    `daily_profit` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '当日收益',
    `holding_profit` DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT '持有收益',
    `holding_profit_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '持有收益率百分比',
    `annualized_return_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '年化收益率百分比',
    `max_drawdown_rate` DECIMAL(10,4) DEFAULT NULL COMMENT '最大回撤百分比',
    `asset_allocation` JSON COMMENT '资产配置快照JSON',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_biz_user_daily_snapshot` (`tenant_id`, `user_id`, `portfolio_id`, `holding_id`, `snapshot_date`, `snapshot_type`),
    KEY `idx_biz_user_daily_snapshot_user` (`tenant_id`, `user_id`, `snapshot_date`),
    KEY `idx_biz_user_daily_snapshot_fund` (`tenant_id`, `fund_id`, `snapshot_date`),
    CONSTRAINT `fk_biz_user_snapshot_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_snapshot_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_snapshot_portfolio` FOREIGN KEY (`portfolio_id`) REFERENCES `biz_user_portfolio` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_snapshot_holding` FOREIGN KEY (`holding_id`) REFERENCES `biz_user_fund_holding` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_snapshot_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户基金每日收益快照表';

CREATE TABLE IF NOT EXISTS `biz_user_alert_rule` (
    `id` BIGINT NOT NULL COMMENT '提醒规则ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `fund_id` BIGINT DEFAULT NULL COMMENT '基金ID，关联biz_fund_info.id；为空表示用户级提醒',
    `rule_name` VARCHAR(128) NOT NULL COMMENT '提醒名称',
    `rule_type` VARCHAR(32) NOT NULL COMMENT '提醒类型: NAV净值 ESTIMATE估值 PROFIT收益 SIP定投 DIVIDEND分红',
    `compare_operator` VARCHAR(16) DEFAULT NULL COMMENT '比较符: GT大于 GTE大于等于 LT小于 LTE小于等于 EQ等于',
    `threshold_value` DECIMAL(20,6) DEFAULT NULL COMMENT '阈值',
    `notify_channels` VARCHAR(128) NOT NULL DEFAULT 'IN_APP' COMMENT '通知渠道，多个用逗号分隔',
    `last_trigger_time` DATETIME(0) DEFAULT NULL COMMENT '最近触发时间',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0禁用 1启用',
    `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_user_alert_rule_user` (`tenant_id`, `user_id`, `status`),
    KEY `idx_biz_user_alert_rule_fund` (`tenant_id`, `fund_id`, `rule_type`),
    CONSTRAINT `fk_biz_user_alert_rule_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_alert_rule_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_alert_rule_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户提醒规则表';

CREATE TABLE IF NOT EXISTS `biz_user_alert_log` (
    `id` BIGINT NOT NULL COMMENT '提醒日志ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `rule_id` BIGINT DEFAULT NULL COMMENT '提醒规则ID，关联biz_user_alert_rule.id',
    `fund_id` BIGINT DEFAULT NULL COMMENT '基金ID，关联biz_fund_info.id',
    `alert_title` VARCHAR(128) NOT NULL COMMENT '提醒标题',
    `alert_content` VARCHAR(1024) NOT NULL COMMENT '提醒内容',
    `trigger_value` DECIMAL(20,6) DEFAULT NULL COMMENT '触发值',
    `notify_channel` VARCHAR(32) NOT NULL DEFAULT 'IN_APP' COMMENT '通知渠道',
    `notify_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '通知状态: PENDING待发送 SENT已发送 FAILED失败 READ已读',
    `trigger_time` DATETIME(0) NOT NULL COMMENT '触发时间',
    `read_time` DATETIME(0) DEFAULT NULL COMMENT '读取时间',
    `failure_reason` VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_user_alert_log_user` (`tenant_id`, `user_id`, `trigger_time`),
    KEY `idx_biz_user_alert_log_status` (`tenant_id`, `notify_status`, `trigger_time`),
    KEY `idx_biz_user_alert_log_rule` (`tenant_id`, `rule_id`),
    CONSTRAINT `fk_biz_user_alert_log_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_alert_log_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_alert_log_rule` FOREIGN KEY (`rule_id`) REFERENCES `biz_user_alert_rule` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_user_alert_log_fund` FOREIGN KEY (`fund_id`) REFERENCES `biz_fund_info` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户提醒通知日志表';

CREATE TABLE IF NOT EXISTS `biz_data_import_batch` (
    `id` BIGINT NOT NULL COMMENT '导入批次ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `user_id` BIGINT NOT NULL COMMENT '用户ID，关联sys_user.id',
    `import_type` VARCHAR(32) NOT NULL COMMENT '导入类型: HOLDING持仓 TRANSACTION交易 NAV净值',
    `file_name` VARCHAR(255) DEFAULT NULL COMMENT '文件名称',
    `file_url` VARCHAR(512) DEFAULT NULL COMMENT '文件地址',
    `total_count` INT NOT NULL DEFAULT 0 COMMENT '总记录数',
    `success_count` INT NOT NULL DEFAULT 0 COMMENT '成功记录数',
    `failure_count` INT NOT NULL DEFAULT 0 COMMENT '失败记录数',
    `import_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '导入状态: PENDING待处理 PROCESSING处理中 SUCCESS成功 PARTIAL部分成功 FAILED失败',
    `failure_reason` TEXT COMMENT '失败原因',
    `start_time` DATETIME(0) DEFAULT NULL COMMENT '开始时间',
    `finish_time` DATETIME(0) DEFAULT NULL COMMENT '完成时间',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_data_import_user` (`tenant_id`, `user_id`, `create_time`),
    KEY `idx_biz_data_import_status` (`tenant_id`, `import_status`, `create_time`),
    CONSTRAINT `fk_biz_data_import_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_biz_data_import_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务数据导入批次表';

CREATE TABLE IF NOT EXISTS `biz_data_sync_log` (
    `id` BIGINT NOT NULL COMMENT '同步日志ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID，关联sys_tenant.id',
    `sync_type` VARCHAR(32) NOT NULL COMMENT '同步类型: FUND_INFO基金信息 NAV净值 ESTIMATE估值 DIVIDEND分红',
    `source` VARCHAR(64) NOT NULL COMMENT '数据来源',
    `biz_date` DATE DEFAULT NULL COMMENT '业务日期',
    `start_time` DATETIME(0) NOT NULL COMMENT '开始时间',
    `finish_time` DATETIME(0) DEFAULT NULL COMMENT '完成时间',
    `total_count` INT NOT NULL DEFAULT 0 COMMENT '总记录数',
    `success_count` INT NOT NULL DEFAULT 0 COMMENT '成功记录数',
    `failure_count` INT NOT NULL DEFAULT 0 COMMENT '失败记录数',
    `sync_status` VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT '同步状态: PROCESSING处理中 SUCCESS成功 PARTIAL部分成功 FAILED失败',
    `failure_reason` TEXT COMMENT '失败原因',
    `create_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '创建人',
    `update_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '修改人',
    `create_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `update_time` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `del_flag` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '0' COMMENT '删除标记，0未删除，1已删除',
    PRIMARY KEY (`id`),
    KEY `idx_biz_data_sync_type_date` (`tenant_id`, `sync_type`, `biz_date`),
    KEY `idx_biz_data_sync_status` (`tenant_id`, `sync_status`, `start_time`),
    CONSTRAINT `fk_biz_data_sync_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenant` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务数据同步日志表';
